version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      DB_HOST: db  # เปลี่ยนจาก localhost เป็น db
      DB_USER: root  # เปลี่ยนเป็นชื่อผู้ใช้ใหม่
      DB_PASS: 1111  # เปลี่ยนรหัสผ่านให้ตรงกัน
      DB_NAME: db
    depends_on:
      - db
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root  # เปลี่ยนให้ตรงกับ DB_USER
      PMA_PASSWORD: 1111  # เปลี่ยนให้ตรงกับ DB_PASS

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root  # เปลี่ยนชื่อผู้ใช้ที่นี่ด้วย
      MYSQL_PASSWORD: 1111  # เปลี่ยนรหัสผ่านให้ตรงกัน
      MYSQL_ROOT_PASSWORD: 1111  # รหัสผ่านสำหรับ root
    ports:
      - "3306:3306"
