version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: 1111
      DB_NAME: db
    depends_on:
      - db
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: 1111

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3306:3306"
